-- Q1.1

SELECT sum(LO_EXTENDEDPRICE * LO_DISCOUNT) AS revenue
FROM lineorder
WHERE toYear(LO_ORDERDATE) = 1993 
  AND LO_DISCOUNT >= 1 AND LO_DISCOUNT <= 3 AND LO_QUANTITY < 25
  
-- Q1.2

SELECT sum(LO_EXTENDEDPRICE * LO_DISCOUNT) AS revenue
FROM lineorder
WHERE toYYYYMM(LO_ORDERDATE) = 199401 
  AND LO_DISCOUNT >= 4 AND LO_DISCOUNT <= 6 AND LO_QUANTITY >= 26 AND LO_QUANTITY <= 35

-- Q1.3

SELECT sum(LO_EXTENDEDPRICE * LO_DISCOUNT) AS revenue
FROM lineorder
WHERE toISOWeek(LO_ORDERDATE) = 6 AND toYear(LO_ORDERDATE) = 1994 
  AND LO_DISCOUNT >= 5 AND LO_DISCOUNT <= 7 AND LO_QUANTITY >= 26 AND LO_QUANTITY <= 35

-- Q3.3

SELECT C_CITY, S_CITY, toYear(LO_ORDERDATE) AS year,
       щтSUM(LO_REVENUE) AS revenue
FROM lineorder
WHERE ((C_CITY = 'UNITED KI1') OR (C_CITY = 'UNITED KI5')) AND ((S_CITY = 'UNITED KI1') OR (S_CITY = 'UNITED KI5')) AND (year >= 1992) AND (year <= 1997)
GROUP BY
C_CITY,
S_CITY,
year
ORDER BY
year ASC,
revenue DESC